#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# symlink config folders
for dir in posters data; do
    mkdir -p "/config/${dir}"
    if [ "$(readlink /app/www/public/${dir})" != "/config/${dir}" ]; then
        rm -rf "/app/www/public/${dir}"
        ln -s "/config/${dir}" "/app/www/public/${dir}"
        lsiown abc:abc "/config/${dir}" "/app/www/public/${dir}"
    fi
done

# create posters sub-folders
mkdir -p \
    /config/posters/movies \
    /config/posters/tv-shows \
    /config/posters/tv-seasons \
    /config/posters/collections
lsiown -R abc:abc /config/posters
